controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rover_ackermann_controller:
      type: ackermann_steering_controller/AckermannSteeringController


rover_ackermann_controller:
  ros__parameters:

    traction_joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint

    steering_joints:
      - front_left_steering_joint
      - front_right_steering_joint

    wheelbase: 0.60

    traction_track_width: 0.56

    steering_track_width: 0.56

    wheel_radius: 0.12

    reference_timeout: 2.0

    publish_rate: 50.0

    use_stamped_vel: false
